Repository HKDAQ/TriggerApplication, pull requests merged in 2020-04, with the labels that each got.

#28 Make Setup.sh sourceable from other directories.
  Setup.sh
Labels: question

#41 Energetic BONSAI doesn't actually require BONSAI
  README.md
  Setup.sh
Labels: Waiting For Review

#38 Stopwatch
  CONTRIBUTING.md
  DataModel/Stopwatch.cpp
  DataModel/Stopwatch.h
  UserTools/BONSAI/BONSAI.cpp
  UserTools/DataOut/DataOut.cpp
  UserTools/EnergeticBONSAI/EnergeticBONSAI.cpp
  UserTools/ReconDataOut/ReconDataOut.cpp
  UserTools/WCSimReader/WCSimReader.cpp
  UserTools/nhits/README.md
  UserTools/nhits/nhits.cpp
  UserTools/nhits/nhits.h
  UserTools/template/MyTool.cpp
  UserTools/template/MyTool.h
  UserTools/template/README.md
  configfiles/SNTriggering/ToolChainConfig
  configfiles/WCSimBONSAI/ToolChainConfig
  configfiles/WCSimBONSAI/nhitsToolConfig
  configfiles/WCSimReaderTest/ToolChainConfig
  configfiles/WCSimReaderTest/nhitsToolConfig
Labels: question

#45 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: PR READY BEN!!!!!!

#46 Update .travis.yml
  .travis.yml
Labels: Waiting For Review, bug

#30 Realistic SubSample times
  CONTRIBUTING.md
  DataModel/DataModel.cpp
  DataModel/DataModel.h
  DataModel/README.md
  DataModel/SubSample.cpp
  DataModel/SubSample.h
  DataModel/TimeDelta.cpp
  DataModel/TimeDelta.h
  DataModel/TriggerInfo.cpp
  DataModel/TriggerInfo.h
  Setup.sh
  UserTools/DataOut/DataOut.cpp
  UserTools/Factory/Factory.cpp
  UserTools/PrepareSubSamples/PrepareSubSamples.cpp
  UserTools/PrepareSubSamples/PrepareSubSamples.h
  UserTools/PrepareSubSamples/README.md
  UserTools/Unity.cpp
  UserTools/WCSimReader/WCSimReader.cpp
  UserTools/nhits/README.md
  UserTools/nhits/nhits.cpp
  UserTools/nhits/nhits.h
  configfiles/WCSimBONSAI/BONSAIToolConfig
  configfiles/WCSimBONSAI/NHitsToolConfig
  configfiles/WCSimBONSAI/PrepareSubSamplesConfig
  configfiles/WCSimBONSAI/ToolsConfig
  configfiles/WCSimReaderTest/DataOutToolConfig
  configfiles/WCSimReaderTest/NHitsToolConfig
  configfiles/WCSimReaderTest/PrepareSubSamplesConfig
  configfiles/WCSimReaderTest/ToolsConfig
Labels: ISSUE

#48 Fix/patch TimeDelta
  DataModel/README.md
  DataModel/TimeDelta.cpp
Labels: PR READY BEN!!!!!!

#52 Feature/recon time handling
  DataModel/ReconInfo.cpp
  DataModel/ReconInfo.h
  UserTools/BONSAI/BONSAI.cpp
  UserTools/DataOut/DataOut.cpp
  UserTools/DataOut/DataOut.h
  UserTools/ReconDataOut/ReconDataOut.cpp
  UserTools/WCSimReader/WCSimReader.cpp
  UserTools/dimfit/dimfit.cpp
  UserTools/dimfit/dimfit.h
Labels: PR READY BEN!!!!!!

#54 Turn on stopwatch for all tools
  UserTools/BONSAI/BONSAI.cpp
  UserTools/BONSAI/BONSAI.h
  UserTools/DataOut/DataOut.cpp
  UserTools/DataOut/DataOut.h
  UserTools/EnergeticBONSAI/EnergeticBONSAI.cpp
  UserTools/EnergeticBONSAI/EnergeticBONSAI.h
  UserTools/PrepareSubSamples/PrepareSubSamples.cpp
  UserTools/PrepareSubSamples/PrepareSubSamples.h
  UserTools/ReconDataIn/ReconDataIn.cpp
  UserTools/ReconDataIn/ReconDataIn.h
  UserTools/ReconDataOut/ReconDataOut.cpp
  UserTools/ReconDataOut/ReconDataOut.h
  UserTools/ReconFilter/ReconFilter.cpp
  UserTools/ReconFilter/ReconFilter.h
  UserTools/ReconRandomiser/ReconRandomiser.cpp
  UserTools/ReconRandomiser/ReconRandomiser.h
  UserTools/ReconReset/ReconReset.cpp
  UserTools/ReconReset/ReconReset.h
  UserTools/WCSimReader/WCSimReader.cpp
  UserTools/WCSimReader/WCSimReader.h
  UserTools/dimfit/dimfit.cpp
  UserTools/dimfit/dimfit.h
  UserTools/template/MyTool.h
  UserTools/test_vertices/test_vertices.cpp
  UserTools/test_vertices/test_vertices.h
  configfiles/SNTriggering/ReconDataInToolConfig
  configfiles/SNTriggering/ReconDataOutToolConfig
  configfiles/SNTriggering/ReconFilterToolConfig
  configfiles/SNTriggering/ReconRandomiserToolConfig
  configfiles/SNTriggering/ReconResetToolConfig
  configfiles/SNTriggering/dimfitToolConfig
  configfiles/WCSimBONSAI/BONSAIToolConfig
  configfiles/WCSimBONSAI/DataOutToolConfig
  configfiles/WCSimBONSAI/EnergeticBONSAIToolConfig
  configfiles/WCSimBONSAI/ReconDataOutToolConfig
  configfiles/WCSimBONSAI/ReconResetToolConfig
  configfiles/WCSimBONSAI/WCSimReaderToolConfig
  configfiles/WCSimReaderTest/DataOutToolConfig
  configfiles/WCSimReaderTest/PrepareSubSamplesConfig
  configfiles/WCSimReaderTest/WCSimReaderToolConfig
Labels: Waiting For Review

#53 Feature/save energy
  DataModel/ReconInfo.cpp
  DataModel/ReconInfo.h
  UserTools/EnergeticBONSAI/EnergeticBONSAI.cpp
  UserTools/ReconDataIn/ReconDataIn.cpp
  UserTools/ReconDataIn/ReconDataIn.h
  UserTools/ReconDataOut/ReconDataOut.cpp
  UserTools/ReconDataOut/ReconDataOut.h
Labels: Conflict
